### ISSUE TITLE
Contact boxenergie

### ISSUE THREAD

**Issue by sunsharebox** [tdouez/TeleinfoMySensors#1]
Bonjour,
Je développe la boxenergie pour les particuliers qui veulent faire des économies d'énergie ou ont du solaire en autoconsommation.(http://demo.sunshare.fr)
Ce projet est opensource sur base raspberry avec liaison filaire sur linky et compteur à impulsion.
Votre solution est intéressante. Je vais la tester sur mon linky.
Je suis en mode standard (115200 BAUD), est ce possible ?
Pourrais on ajouter le traitement des impulsions à votre module radio ?
Il y a plusieurs projets en cours dans la communauté (electronique et informatique) avec l'école polytech de Nantes. Vous pouvez rejoindre notre communauté.
Crdlt.

**Comment by tdouez** [comment]
Bonjour,
  Le module est compatible avec le mode  historique en 1200bauds et le nouveau mode en 9600bauds mais la partie logicielle qui a été écrite pour le 1200bauds. Pour le mode impulsionnel il faut aller sur le site de MySensors il y a la description du capteur pour ce mode.

Tristan

Le 6 févr. 2020 à 00:25, sunshare <notifications@github.com> a écrit :

﻿

Bonjour,
Je développe la boxenergie pour les particuliers qui veulent faire des économies d'énergie ou ont du solaire en autoconsommation.(http://demo.sunshare.fr)
Ce projet est opensource sur base raspberry avec liaison filaire sur linky et compteur à impulsion.
Votre solution est intéressante. Je vais la tester sur mon linky.
Je suis en mode standard (115200 BAUD), est ce possible ?
Pourrais on ajouter le traitement des impulsions à votre module radio ?
Il y a plusieurs projets en cours dans la communauté (electronique et informatique) avec l'école polytech de Nantes. Vous pouvez rejoindre notre communauté.
Crdlt.

**Comment by sunsharebox** [comment]
Merci, c'est genial.
Ca vous interesse un hackathon en septembre 2020 pendant la nantes digital week ? Je tache d'organiser avec enedis un banc de linky pour des dev open-source.
Julien.
-- envoyé de mon mobile
julien.moreau@sunshare.fr
M:06 51 76 10 42
http://sunshare.fr - Partage d'électricité

**Comment by tdouez** [comment]
Bonjour,

    C’est une bonne idée mais je ne suis pas de la région et je ne suis pas trop intéressé.
    Pour rappel mon module est open source mais il y a quand même une licence. Il est possible de le modifier, de faire une autre version à la condition de citer la source, moi donc ;).

Tristan

Le 6 févr. 2020 à 08:49, sunshare <notifications@github.com> a écrit :

﻿Merci, c'est genial.
Ca vous interesse un hackathon en septembre 2020 pendant la nantes digital week ? Je tache d'organiser avec enedis un banc de linky pour des dev open-source.
Julien.
-- envoyé de mon mobile
julien.moreau@sunshare.fr
M:06 51 76 10 42
http://sunshare.fr - Partage d'électricité
