### ISSUE TITLE
Envois trames à la Gateway

### ISSUE THREAD

**Issue by secator76** [tdouez/TeleinfoMySensors#10]
Bonjour Tristan,

tu initialises 2 variables : 

const unsigned long SEND_FREQUENCY_FULL = 180000; // 3mn, Minimum time between send (in milliseconds). 
const unsigned long SEND_FREQUENCY_TIC  =  15000; // 15s,  Minimum time between send (in milliseconds). 

qui permettent d'envoyer les trames à la gateway toutes les 3 minutes ou toutes les 15 secondes or ces variables sont ensuite utilisées nulle part dans le programme ce qui fait que la gateway est bombardées de trames et par voie de conséquence mon domoticz aussi. Comment faire pour utiliser ces variables.

Ensuite que faut il modifier pour envoyer EAST,EASF01,EASF02...EASF10 en Kwh (avec 3 chifffres après la virgule) et non pas en wh car domoticz crée un capteur qui attend des Kwh.

Merci.

**Comment by tdouez** [comment]
Bonjour,
    Pour cela tu es obligé de changer la valeur des constantes, recompiler le code et flasher l’arduino. Le code actuel ne permet pas de mettre à jour ces valeurs via un envoi gateway vers le module Linky. Je peux mettre cela dans ma « todo list » ;)

    La même chose pour les champs en watt/heure, je peux prévoir une commande de pour les passer en kwh. En attendant, il faut modifier le code lors des commandes « send(…. ».

Tristan

Le 29 janv. 2023 à 09:57, secator76 ***@***.***> a écrit :

﻿

Bonjour Tristan,

tu initialises 2 variables :

const unsigned long SEND_FREQUENCY_FULL = 180000; // 3mn, Minimum time between send (in milliseconds).
const unsigned long SEND_FREQUENCY_TIC = 15000; // 15s, Minimum time between send (in milliseconds).

qui permettent d'envoyer les trames à la gateway toutes les 3 minutes ou toutes les 15 secondes or ces variables sont ensuite utilisées nulle part dans le programme ce qui fait que la gateway est bombardées de trames et par voie de conséquence mon domoticz aussi. Comment faire pour utiliser ces variables.

Ensuite que faut il modifier pour envoyer EAST,EASF01,EASF02...EASF10 en Kwh (avec 3 chifffres après la virgule) et non pas en wh car domoticz créé un capteur qui attends des Kwh.

Merci.

**Comment by secator76** [comment]
Bonsoir,

merci pour ta réponse mais je ne suis pas assez calé pour faire ces modifications sur ta dernière version. En attendant une eventuelle prise en compte dans tes prochaines versions, je vais me rabattre sur la 1.1.6 qui est plus de mon niveau et que je vais pouvoir modifier selon mes besoins.
En tout cas merci pour ton travail. ça fonctionne très bien.

Bonne soirée.

**Comment by tdouez** [comment]
Une version 2.1.0 est en cours de dev pour ajouter la possibilité de modifier les temps de mise à jour.

**Comment by secator76** [comment]
ok, merci. Une possibilité d'envoyer en kWh et non en Wh et c'est parfait.
