### ISSUE TITLE
Pas de remontée dans HA

### ISSUE THREAD

**Issue by ayu69** [tdouez/TeleinfoMySensors#11]
Bonjour,

J'ai réceptionné le module cette semaine, je l'ai programmé, puis raccorder jusque la pas de souci, ma passerelle voit bien le module.

En revanche sur Homeassistant je n'ai que ça :

![image](https://user-images.githubusercontent.com/5493933/218257625-397bbb1a-9acd-463b-a3db-b043029edcd9.png)

et je n'arrive pas à comprendre comment récupérer les différentes infos

Merci d'avance

**Comment by tdouez** [comment]
Bonjour,
   Je ne connais pas bien Hope assistant étant sous Jeedom. Je suppose que tu passe par un module Mysensors sur le HA, il devrait avoir la possibilité de voir les logs afin de vérifier les donnés brutes.
   Au démarrage le module Linky passe par l’étape de présentation pour lister l’ensemble des étiquettes qui seront alimentées ensuite. Tu devrais avoir cela dans les logs.

   Tristan


Le 11 févr. 2023 à 13:21, Quentin Marques ***@***.***> a écrit :

﻿

Bonjour,

J'ai réceptionné le module cette semaine, je l'ai programmé, puis raccorder jusque la pas de souci, ma passerelle voit bien le module.

En revanche sur Homeassistant je n'ai que ça :

[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5493933%2F218257625-397bbb1a-9acd-463b-a3db-b043029edcd9.png&data=05%7C01%7C%7C122c22974e674a23fa6208db0c2a7f4c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638117148875828608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6jgAm4RwL4E4biXYJjyWemsvtEvlh9c9tyTWm0tydWM%3D&reserved=0>

et je n'arrive pas à comprendre comment récupérer les différentes infos

Merci d'avance

**Comment by ayu69** [comment]
Bonjour,

Autant le module se présente effectivement bien à ma paserelle, voila ce que j'ai dans le json :

`    "10": {
        "sensor_id": 10,
        "children": {
            "1": {
                "id": 1,
                "type": 36,
                "description": "ADSC",
                "values": {}
            },
            "2": {
                "id": 2,
                "type": 36,
                "description": "VTIC",
                "values": {}
            },
            "3": {
                "id": 3,
                "type": 36,
                "description": "DATE",
                "values": {}
            },
            "4": {
                "id": 4,
                "type": 36,
                "description": "NGTF",
                "values": {}
            },
            "5": {
                "id": 5,
                "type": 36,
                "description": "LTARF",
                "values": {}
            },
            "6": {
                "id": 6,
                "type": 13,
                "description": "EAST",
                "values": {}
            },
            "7": {
                "id": 7,
                "type": 13,
                "description": "EASF01",
                "values": {}
            },
            "8": {
                "id": 8,
                "type": 13,
                "description": "EASF02",
                "values": {}
            },
            "9": {
                "id": 9,
                "type": 13,
                "description": "EASF03",
                "values": {}
            },
            "10": {
                "id": 10,
                "type": 13,
                "description": "EASF04",
                "values": {}
            },
            "11": {
                "id": 11,
                "type": 13,
                "description": "EASF05",
                "values": {}
            },
            "12": {
                "id": 12,
                "type": 13,
                "description": "EASF06",
                "values": {}
            },
            "13": {
                "id": 13,
                "type": 13,
                "description": "EASF07",
                "values": {}
            },
            "14": {
                "id": 14,
                "type": 13,
                "description": "EASF08",
                "values": {}
            },
            "15": {
                "id": 15,
                "type": 13,
                "description": "EASF09",
                "values": {}
            },
            "16": {
                "id": 16,
                "type": 13,
                "description": "EASF10",
                "values": {}
            },
            "17": {
                "id": 17,
                "type": 13,
                "description": "EASD01",
                "values": {}
            },
            "18": {
                "id": 18,
                "type": 13,
                "description": "EASD02",
                "values": {}
            },
            "19": {
                "id": 19,
                "type": 13,
                "description": "EASD03",
                "values": {}
            },
            "20": {
                "id": 20,
                "type": 13,
                "description": "EASD04",
                "values": {}
            },
            "21": {
                "id": 21,
                "type": 13,
                "description": "EAIT",
                "values": {}
            },
            "22": {
                "id": 22,
                "type": 13,
                "description": "ERQ1",
                "values": {}
            },
            "23": {
                "id": 23,
                "type": 13,
                "description": "ERQ2",
                "values": {}
            },
            "24": {
                "id": 24,
                "type": 13,
                "description": "ERQ3",
                "values": {}
            },
            "25": {
                "id": 25,
                "type": 13,
                "description": "ERQ4",
                "values": {}
            },
            "26": {
                "id": 26,
                "type": 30,
                "description": "IRMS1",
                "values": {}
            },
            "27": {
                "id": 27,
                "type": 30,
                "description": "IRMS2",
                "values": {}
            },
            "28": {
                "id": 28,
                "type": 30,
                "description": "IRMS3",
                "values": {}
            },
            "29": {
                "id": 29,
                "type": 30,
                "description": "URMS1",
                "values": {}
            },
            "30": {
                "id": 30,
                "type": 30,
                "description": "URMS2",
                "values": {}
            },
            "31": {
                "id": 31,
                "type": 30,
                "description": "URMS3",
                "values": {}
            },
            "32": {
                "id": 32,
                "type": 13,
                "description": "PREF",
                "values": {}
            },
            "33": {
                "id": 33,
                "type": 13,
                "description": "PCOUP",
                "values": {}
            },
            "34": {
                "id": 34,
                "type": 13,
                "description": "SINSTS",
                "values": {}
            },
            "35": {
                "id": 35,
                "type": 13,
                "description": "SINSTS1",
                "values": {}
            },
            "36": {
                "id": 36,
                "type": 13,
                "description": "SINSTS2",
                "values": {}
            },
            "37": {
                "id": 37,
                "type": 13,
                "description": "SINSTS3",
                "values": {}
            },
            "38": {
                "id": 38,
                "type": 13,
                "description": "SMAXSN",
                "values": {}
            },
            "39": {
                "id": 39,
                "type": 13,
                "description": "SMAXSN1",
                "values": {}
            },
            "40": {
                "id": 40,
                "type": 13,
                "description": "SMAXSN2",
                "values": {}
            },
            "41": {
                "id": 41,
                "type": 13,
                "description": "SMAXSN3",
                "values": {}
            },
            "42": {
                "id": 42,
                "type": 13,
                "description": "SMAXSN-1",
                "values": {}
            },
            "43": {
                "id": 43,
                "type": 13,
                "description": "SMAXSN1-1",
                "values": {}
            },
            "44": {
                "id": 44,
                "type": 13,
                "description": "SMAXSN2-1",
                "values": {}
            },
            "45": {
                "id": 45,
                "type": 13,
                "description": "SMAXSN3-1",
                "values": {}
            },
            "46": {
                "id": 46,
                "type": 13,
                "description": "SINSTI",
                "values": {}
            },
            "47": {
                "id": 47,
                "type": 13,
                "description": "SMAXIN",
                "values": {}
            },
            "48": {
                "id": 48,
                "type": 13,
                "description": "SMAXIN-1",
                "values": {}
            },
            "49": {
                "id": 49,
                "type": 13,
                "description": "CCASN",
                "values": {}
            },
            "50": {
                "id": 50,
                "type": 13,
                "description": "CCASN-1",
                "values": {}
            },
            "51": {
                "id": 51,
                "type": 13,
                "description": "CCAIN",
                "values": {}
            },
            "52": {
                "id": 52,
                "type": 13,
                "description": "CCAIN-1",
                "values": {}
            },
            "53": {
                "id": 53,
                "type": 30,
                "description": "UMOY1",
                "values": {}
            },
            "54": {
                "id": 54,
                "type": 30,
                "description": "UMOY2",
                "values": {}
            },
            "55": {
                "id": 55,
                "type": 30,
                "description": "UMOY3",
                "values": {}
            },
            "56": {
                "id": 56,
                "type": 36,
                "description": "STGE",
                "values": {}
            },
            "57": {
                "id": 57,
                "type": 36,
                "description": "DPM1",
                "values": {}
            },
            "58": {
                "id": 58,
                "type": 36,
                "description": "DPM2",
                "values": {}
            },
            "59": {
                "id": 59,
                "type": 36,
                "description": "DPM3",
                "values": {}
            },
            "60": {
                "id": 60,
                "type": 36,
                "description": "FPM1",
                "values": {}
            },
            "61": {
                "id": 61,
                "type": 36,
                "description": "FPM2",
                "values": {}
            },
            "62": {
                "id": 62,
                "type": 36,
                "description": "FPM3",
                "values": {}
            },
            "63": {
                "id": 63,
                "type": 36,
                "description": "MSG1",
                "values": {}
            },
            "64": {
                "id": 64,
                "type": 36,
                "description": "MSG2",
                "values": {}
            },
            "65": {
                "id": 65,
                "type": 36,
                "description": "PRM",
                "values": {}
            },
            "66": {
                "id": 66,
                "type": 36,
                "description": "RELAIS",
                "values": {}
            },
            "67": {
                "id": 67,
                "type": 36,
                "description": "NTARF",
                "values": {}
            },
            "68": {
                "id": 68,
                "type": 36,
                "description": "NJOURF",
                "values": {}
            },
            "69": {
                "id": 69,
                "type": 36,
                "description": "NJOURF+1",
                "values": {}
            },
            "70": {
                "id": 70,
                "type": 36,
                "description": "PJOURF+1",
                "values": {}
            },
            "71": {
                "id": 71,
                "type": 36,
                "description": "PPOINTE",
                "values": {}
            },
            "99": {
                "id": 99,
                "type": 36,
                "description": "START",
                "values": {}
            }
        },
        "type": 17,
        "sketch_name": "Teleinfo",
        "sketch_version": "v2.0.3",
        "battery_level": 0,
        "protocol_version": "2.3.2",
        "heartbeat": 0
    },`

En revanche, je remarque qu'une fois les présentation faites, il ne renvoie plus jamais d'infos à la passerelle

**Comment by tdouez** [comment]
Ce problème peux avoir plusieurs causes : le logiciel en lui même, un problème hardware ou la non activation de la sortie TIC sur le compteur. Pour le côté logiciel, je ne pense pas mais je vais quand même vérifier suite à la mise à jour récente. Pour l'activation du TIC sur le compteur, il faut demander à EDF. As tu un module fdti récupéré la trame brute depuis l'arduino ?
Je vais vérifier de mon côté.

**Comment by tdouez** [comment]
Côté journal HA/Mysensors, tu as quelles informations ?

**Comment by ayu69** [comment]
Bonjour,

Désolé pour le délais.

C'est bien le problème, je n'ai pas de log, car le module ne renvoi jamais d'infos(aucune led ne clignote depuis le dernier branchement ), la seule remonté est celle a la mise sous tension.

Cela me paraîtrait étrange de ne pas avoir le tic actif, car juste avant j'avais le module atome de chez direct énergie, donc ça devrait toujours fonctionné non ?

**Comment by ayu69** [comment]
> Ce problème peux avoir plusieurs causes : le logiciel en lui même, un problème hardware ou la non activation de la sortie TIC sur le compteur. Pour le côté logiciel, je ne pense pas mais je vais quand même vérifier suite à la mise à jour récente. Pour l'activation du TIC sur le compteur, il faut demander à EDF. As tu un module fdti récupéré la trame brute depuis l'arduino ? Je vais vérifier de mon côté.

Étant en déplacement toute la semaine, je pourrais regarder plus en détails ce weekend

**Comment by ayu69** [comment]
j'ai essayé quelque chose d'autres.

J'ai passé ma passerelle en mysensors MQTT 

et voila ce que j'obtiens avec mqttexplorer :
![image](https://user-images.githubusercontent.com/5493933/219864990-151581a9-ca2f-4098-b0a8-ffe73c8c3a69.png)

Donc en soit toutes les 20 minutes environ une trame est envoyé, mais rien dans cette trame...

**Comment by tdouez** [comment]
Le passage par une gateway de type mqtt demande le forçage de l’ID du module. As tu forcer l’ID en utilisant les micro switchs ?

Bon je pense que je vais t’envoyer un autre module car j’ai quand même l’impression qu’il y a un souci hardware.

   Peux tu me rappeler ton adresse stp via l'adresse mail mail@fumeebleue.fr ? Edit : Pas besoin, je l'ai retrouvé dans les commandes. ;)

 Tristan

Le 18 févr. 2023 à 13:11, Quentin Marques ***@***.***> a écrit :

﻿

j'ai essayé quelque chose d'autres.

J'ai passé ma passerelle en mysensors MQTT

et voila ce que j'obtiens avec mqttexplorer :
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5493933%2F219864990-151581a9-ca2f-4098-b0a8-ffe73c8c3a69.png&data=05%7C01%7C%7Ca07503612fbc40a65e4308db11a93a7c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638123190740624780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Y%2F9d4X2kYhig8sbKfVi3%2Fg2%2FDp2V8mu2pqkvrvxFwTQ%3D&reserved=0>

Donc en soit toutes les 20 minutes environ une trame est envoyé, mais rien dans cette trame...

**Comment by ayu69** [comment]
Oui j'ai assez rapidement fixé l'ID avec les microswitch, dans le doute que cela puisse venir de la mais visiblement rien

Tu pense vraiment à un souci hardware ?

**Comment by tdouez** [comment]
Peux tu me faire une photo du circuit d’alimentation? Il y a un mosfet juste à droite de l’optocoupleur. A voir si il y a pas un souci de soudure.

Le 18 févr. 2023 à 17:42, Quentin Marques ***@***.***> a écrit :

﻿

Oui j'ai assez rapidement fixé l'ID avec les microswitch, dans le doute que cela puisse venir de la mais visiblement rien

Tu pense vraiment à un souci hardware ?

**Comment by ayu69** [comment]
![IMG_20230219_114505](https://user-images.githubusercontent.com/5493933/219943287-d7b8f833-8891-449f-bbe5-054046d7fa51.jpg)

Difficile de voir bien

**Comment by tdouez** [comment]
Oui c'est assez difficile. Je viens de t'envoyer un autre module qui est 100% fonctionnel. Peux tu l'utiliser et me faire un retour. Il faudra me renvoyer celui qui est hs.

**Comment by ayu69** [comment]
Aucun souci,
Je te fait un retour dès que possible.

Merci pour ta réactivité.

**Comment by ayu69** [comment]
Bonjour,

Rien à faire j'ai toujours le même souci, du coup on peut exclure le côté matériel.
Je à part le code je ne vois pas vraiment.

Du point de vue de HA j'ai quand même du "mieux" :
![image](https://user-images.githubusercontent.com/5493933/221354732-e868550d-463c-473c-9de0-a07f0274d32c.png)

J'ai maintenant la possibilités d'envoyer des commandes au modules, et lorsque je le fait, la led orange du module linky clignote 1 fois.

Donc la communication se fait bel et bien.

En revanche à part la présentation, aucune valeurs ne s'affiche dans le fichier json....  

Pour moi, le module ne fait que faire les présentations (ce qui fonctionne pour le coup) mais après plus rien.
D'ailleurs si je supprime le périphérique depuis HA, il ne réapparait que si je débranche et rebranche de nouveau le module.
Si il envoyé des trames, il réapparaitrait automatiquement (testé avec mes autres capteurs Mysensors).

**Comment by tdouez** [comment]
Hello,
    Bon ça avance, pas de souci côté matériel. J’ai essayé chez moi le home assistant et j’ai aussi la visu que de la premier étiquette BASE. Je n’arrive pas à avoir les autres, je vais continuer à chercher. Côté code pas de souci car cela fonctionne très bien avec Jeedom.

Tristan

Le 25 févr. 2023 à 12:37, Quentin Marques ***@***.***> a écrit :

﻿

Bonjour,

Rien à faire j'ai toujours le même souci, du coup on peut exclure le côté matériel.
Je à part le code je ne vois pas vraiment.

Du point de vue de HA j'ai quand même du "mieux" :
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5493933%2F221354732-e868550d-463c-473c-9de0-a07f0274d32c.png&data=05%7C01%7C%7Ca904e71b728d4d47804808db1724a729%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638129218401138612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VAS5j11Yc50xhiZCSZhacYeogsYyYw51ynE7iu3kJ4E%3D&reserved=0>

J'ai maintenant la possibilités d'envoyer des commandes au modules, et lorsque je le fait, la led orange du module linky clignote 1 fois.

Donc la communication se fait bel et bien.

En revanche à part la présentation, aucune valeurs ne s'affiche dans le fichier json....
