### ISSUE TITLE
spam de la gateway

### ISSUE THREAD

**Issue by ssdrun** [tdouez/TeleinfoMySensors#12]
Bonjour,

Je vous écris car suite à la mise à jour du firmware vers la v2.0.5, les données sont transmises en permanence, sans délai et/ou sans tenir compte de la mise à jour ou non des données du linky. Cela spam la gateway et j'ai des données erronées très fréquentes qui apparaissent en Home Assistant. pourriez vous m'aider à comprendre la raison s'il vous plait ? bug du firmware ou problème de mon coté ?
Ci-joint un extrait des logs de reception de la gateway depuis HA et une capture d'écran des erreurs (toutes ne sont pas visibles)
Merci,

Samuel
 
[HA-mysensors-gateway-log.txt](https://github.com/tdouez/TeleinfoMySensors/files/11181175/HA-mysensors-gateway-log.txt)
![erreur données HA](https://user-images.githubusercontent.com/120454521/230671592-f25fe067-a72b-46e7-9e61-5671d6ea9a86.png)

**Comment by tdouez** [comment]
Bonjour,
  Ok je vais regarder.
Tristan

Le 7 avr. 2023 à 22:05, ssdrun ***@***.***> a écrit :

﻿

Bonjour,

Je vous écris car suite à la mise à jour du firmware vers la v2.0.5, les données sont transmises en permanence, sans délai et/ou sans tenir compte de la mise à jour ou non des données du linky. Cela spam la gateway et j'ai des données erronées très fréquentes qui apparaissent en Home Assistant. pourriez vous m'aider à comprendre la raison s'il vous plait ? bug du firmware ou problème de mon coté ?
Ci-joint un extrait des logs de reception de la gateway depuis HA et une capture d'écran des erreurs (toutes ne sont pas visibles)
Merci,

Samuel

HA-mysensors-gateway-log.txt<https://github.com/tdouez/TeleinfoMySensors/files/11181175/HA-mysensors-gateway-log.txt>
[erreur données HA]<https://user-images.githubusercontent.com/120454521/230671592-f25fe067-a72b-46e7-9e61-5671d6ea9a86.png>

**Comment by tdouez** [comment]
Tu étais sur quelle version auparavant, la v2.0.4 ? Pour savoir si ce problème est lié à la dernière mise à jour ou suite au changement de librairie libTeleinfo. L'envoi des données via Mysensors est lié au rafraichissement des étiquettes lues par la librairie libTeleinfo; il n'y a pas de réglage actuellement sur la fréquence des send sous Mysensors.
Pour les infos erronées, je n'ai pas encore trouvé la raison, car il y a bien une vérification du checksum avant l'envoi des données.

**Comment by ssdrun** [comment]
J'étais sur la version FB 1.0.6 de mémoire. Tous marchait correctement, avec un envoi des données toutes les 5s je crois.... mais j'ai du monter la version de ma gateway mysensors et la recéption des données à commencée à dérailler. En me rendant sur le site de fumeebleue, je me suis aperçu qu'il y avait eu pas mal de versions entre temps. J'ai donc fait la MAJ.  J'ai vérifié le condensateur c2 et j'ai bien un condensateur c2 de 42uf. Je suis actuellement en version mysensors 2.3.2. Depuis, les données remontes en permanences à priori sans erreurs, mais beaucoup trop fréquemment (cf log). Pour les données erronées dans HA, je pense que ça vient de la gateway qui doit avoir du mal à gérer autant de données simultanées émises par la carte FB. Quoi qu'il en soit, la gateway est littéralement spamée par la carte Linky FB et gère difficilement maintenant mes autres sensors... en zappant des transmissions....  Merci pour ton aide
Samuel

**Comment by tdouez** [comment]
ok, je comprends mieux. Je vais faire une petite évolution de mon code pour gérer cette problématique.

**Comment by tdouez** [comment]
Peux-tu réaliser un test avec cette modification ? J'ai ajouté un délai d'une seconde entre les émissions vers la gateway.
[TeleinfoMySensors.ino.zip](https://github.com/tdouez/TeleinfoMySensors/files/11202654/TeleinfoMySensors.ino.zip)

**Comment by ssdrun** [comment]
ok , je teste et je reviens vers toi,
Merci

**Comment by ssdrun** [comment]
Alors ça semble beaucoup mieux, mais on pourrait gagner en fluidité si on pouvait empecher l'envoi de données non modifiées.
Car sont toujours envoyée à priori toutes les données dont celle qui ne changent jamais : OPTARIF, ISOUSC, PTEC, HHPHC, IMAX, MOTDETAT, ADCO, 
Je te joins le log.
Merci !
Samuel
[HA-mysensors-gateway-log_V2.0.6.txt](https://github.com/tdouez/TeleinfoMySensors/files/11202825/HA-mysensors-gateway-log_V2.0.6.txt)

**Comment by ssdrun** [comment]
mais si cela est trop complexe à gérer, il me suffit peut-etre de commenter les lignes de code qui envoient ces données inutiles...

**Comment by ssdrun** [comment]
Salut,

Alors après une nuit de fonctionnement, les logs montrent encore quelques erreurs. Et cette fois j'ai désactivé quasiment tous mes autres sensors afin de n'avoir que des logs de la carte linky FB. Les erreurs semblent donc venir de la carte... puisque la gateway n'est plus spamée... En fait la seule erreur est sur la donnée BASE: qui par moment est erronée (ci-dessous 4 valeurs proches de 0 trouvées dans les logs).

`2023-04-11 23:15:22.965 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: BASE: value_type 18, value = 0

2023-04-12 00:42:20.842 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: BASE: value_type 18, value = 0

2023-04-12 04:36:27.086 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: BASE: value_type 18, value = 0

2023-04-12 06:22:16.414 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: BASE: value_type 18, value = 580`

Sachant que cette valeur est incrémentielle, ne serait-il pas possible de vérifier que la valeur soit supérieure ou égale à la précédente avant envoi ? avec aussi une sécurité sur la valeur haute au cas où ? (genre  Valeur BASE précédente <= BASE actuelle < BASE +  1000)

Je te joins les logs.
Merci

Samuel
[HA-mysensors-gateway-log_V2.0.6_night.txt](https://github.com/tdouez/TeleinfoMySensors/files/11207025/HA-mysensors-gateway-log_V2.0.6_night.txt)
![Historique  HA](https://user-images.githubusercontent.com/120454521/231347400-5b03abbf-b45c-42db-a8df-3f0a42bff85f.png)

**Comment by tdouez** [comment]
Bonjour,
  Peux-tu refaire un essai avec cette mise à jour ?
[TeleinfoMySensors.ino.zip](https://github.com/tdouez/TeleinfoMySensors/files/11213619/TeleinfoMySensors.ino.zip)

**Comment by ssdrun** [comment]
Salut,
Je viens de le charger. Je le laisse tourner 24h et te fais un retour.
Merci

**Comment by ssdrun** [comment]
Alors, ça a fonctionné impeccable toute la nuit et aujourd'hui jusqu'à ce message recu par la gateway (en gras): 

2023-04-14 15:32:34.802 DEBUG (MainThread) [mysensors.transport] Receiving 27;4;1;0;18;21180817
**2023-04-14 15:33:04.585 DEBUG (MainThread) [mysensors.transport] Receiving 27;4;1;0;18;1094922648**
2023-04-14 15:33:04.657 DEBUG (MainThread) [mysensors.transport] Receiving 27;4;1;0;18;21180824

qui est hors norme part rapport aux valeurs précédentes et suivantes reçues : 
Soit le programme ne fonctionne pas correctement.. mais il me semble bien écrit pour écarter ce type de valeur transmise...donc j'en doute...
Soit j'ai un problème avec la gateway qui "entend" n'importe quoi ... je vais tenter d'isoler le module.. peut-etre est-il trop parasité...

Je tente une amélioration matérielle et retesterai ce week-end...

**Comment by tdouez** [comment]
En effet, le code modifié évite se genre de désagrément. Je vais quand même vérifier mon code.

Le 14 avr. 2023 à 14:44, ssdrun ***@***.***> a écrit :

﻿

Alors, ça a fonctionné impeccable toute la nuit et aujourd'hui jusqu'à ce message recu par la gateway (en gras):

2023-04-14 15:32:34.802 DEBUG (MainThread) [mysensors.transport] Receiving 27;4;1;0;18;21180817
2023-04-14 15:33:04.585 DEBUG (MainThread) [mysensors.transport] Receiving 27;4;1;0;18;1094922648
2023-04-14 15:33:04.657 DEBUG (MainThread) [mysensors.transport] Receiving 27;4;1;0;18;21180824

qui est hors norme part rapport aux valeurs précédentes et suivantes reçues :
Soit le programme ne fonctionne pas correctement.. mais il me semble bien écrit pour écarter ce type de valeur transmise...donc j'en doute...
Soit j'ai un problème avec la gateway qui "entend" n'importe quoi ... je vais tenter d'isoler le module.. peut-etre est-il trop parasité...

Je tente une amélioration matérielle et retesterai ce week-end...

**Comment by tdouez** [comment]
A priori c'est bon. Pas de retour.
