### ISSUE TITLE
Fabrication PCB

### ISSUE THREAD

**Issue by bolosetienne** [tdouez/TeleinfoMySensors#2]
Bonjour,

J'ai vu que vous n'aviez plus de PCB dans votre boutique, vu la période cela risque d'être compliqué d'en faire fabriquer et de les recevoir rapidement.
Pourriez vous me dire sur quel site vous les faites fabriquer si ca ne vous dérange pas, je souhaiterais le faire mais j'avoue que je n'y connais pas grand chose dans ce domaine, le dernier PCB que j'ai du faire c'était en 1998 au collège!
Quels sont les dimensions et les caractéristique que vous conseillez, et quel fichier faut il envoyer le .brd ou le .sch?

Merci

**Comment by tdouez** [comment]
Bonjour,
   Je pense recevoir de nouveaux pcb d’ici une semaine car ils sont arrivés dans les mains de la poste. Un peu de patience.  :)

Tristan

Le 3 avr. 2020 à 20:27, Etienne Laval <notifications@github.com> a écrit :

﻿

Bonjour,

J'ai vu que vous n'aviez plus de PCB dans votre boutique, vu la période cela risque d'être compliqué d'en faire fabriquer et de les recevoir rapidement.
Pourriez vous me dire sur quel site vous les faites fabriquer si ca ne vous dérange pas, je souhaiterais le faire mais j'avoue que je n'y connais pas grand chose dans ce domaine, le dernier PCB que j'ai du faire c'était en 1998 au collège!
Quels sont les dimensions et les caractéristique que vous conseillez, et quel fichier faut il envoyer le .brd ou le .sch?

Merci
