### ISSUE TITLE
Soucis de téléversement

### ISSUE THREAD

**Issue by Marc--** [tdouez/TeleinfoMySensors#3]
Salut et merci beaucoup pour ton travail ! Je cherchais exactement ce genre de montage autonome pour mes deux compteurs Linky !

Je viens de terminer la passerelle, pas de soucis, mais j'ai quelques difficultés avec le module TéléInfo. Lors du téléversement, j'ai une erreur:

exit status 1
'read_teleinfo' was not declared in this scope

Je ne comprend pas d'ou ça vient... j'ai suivi ton tuto, je suis en 3.3v, port COM ok, modèle OK... mais rien à faire.

Une idée ?

Bonne soirée !
[Marc]([url](url
[TeleInfoMySensors_errors.txt](https://github.com/tdouez/TeleinfoMySensors/files/5031707/TeleInfoMySensors_errors.txt)
![2020-08-06 01_21_25-Window](https://user-images.githubusercontent.com/9568739/89474105-f1c38900-d784-11ea-8f3c-cbcb25dd4104.png)

))

**Comment by Marc--** [comment]
Ok, je suis une tanche. Je pense que l'heure à laquelle j'ai fait ça y est pour quelque chose. J'ai simplement oublié de copier le second .ino dans le dossier du projet.

Merci beaucoup pour ton travail !! Hâte de tester en live.

**Comment by tdouez** [comment]
@Marc-- , je suis content pour toi.. :) Merci pour ce retour.
