### ISSUE TITLE
erreur lors du téléchargement

### ISSUE THREAD

**Issue by jbbriois** [tdouez/TeleinfoMySensors#5]
Bonjour,

J'ai une erreur lors du téléchargement du sketch.

`TeleinfoMySensors:179:1: error: declaration does not declare anything [-fpermissive]
 teleinfo_s;
`exit status 1
declaration does not declare anything [-fpermissive]`

**Comment by tdouez** [comment]
il faut mettre les deux fichiers *.ino sur le même répertoire

**Comment by jbbriois** [comment]
oui c'est bien ce que j'ai fait sinon il y aurait d'autres erreurs lors de la compilation.

**Comment by tdouez** [comment]
nouvelle version 1.1.5 qui doit corriger le pb

**Comment by tdouez** [comment]
nouvelle version 1.1.5 qui doit corriger le pb
