### ISSUE TITLE
Valeur fluctuante

### ISSUE THREAD

**Issue by The-MAD-Virus** [tdouez/TeleinfoMySensors#9]
Bonjour,

Tout d'abord merci, cela fait déjà un an que j'utilise ton projet avec Home-Assistant.
Tout marche à merveille, mais ressemant Home-Assistant ajouter une interface pour visualiser la consommation/production de son logement et c'est la que je me suis rendu compte qu'il y avait un problème avec les valeurs retourner.
EASF01 et EASF02 retournent par moment zéro ou la valeur actuelle plus un nombre aléatoire ( ex: 54586 + 528 = 54586528).
Je n'arrive pas à savoir si cela vient du code ou du circuit imprimé.

Pour les valeurs à zéro je vois bien comment corriger le code, mais pour l'autre type d'erreur je n’ai aucune idée.

Voilà je suis preneur de toute piste pour corriger ces erreurs.

**Comment by brag00n** [comment]
Bonjour,

Je constate la même chose sur Jeedom
<img width="765" alt="Issue_HCHP_01" src="https://user-images.githubusercontent.com/35399662/216126196-da4acd0c-b2c9-4791-a5c3-359feddd6c1f.png">

**Comment by tdouez** [comment]
Hello, ok je vais analyser mon code. Vous utilisez quelle version ?

**Comment by The-MAD-Virus** [comment]
Bonjour,

J'utilise la version 2.0.1, malheureusement je n'ai pas d'oscilloscope sous la main pour contrôler mon circuit.
Je me demande si il n’y a pas un problème au niveau du découpage des trames.

**Comment by tdouez** [comment]
Bonjour @The-MAD-Virus  et @brag00n ,
    Pour le récupération des etiquettes TIC dont la série EASF.., j'utilise la librairie libTeleinfo que j'ai légèrement modifiée pour gagner de la place mémoire.  J'ai récupéré la dernière version de cette librairie avec un correctif notamment sur des problèmes d'interruptions de trame qui peut engendrer des valeurs incohérentes.
    Je vais donc mettre en ligne ce correctif avec la version 2.0.3.

     Je garde l'incident ouvert. Avez-vous la possibilité de récupérer cette dernière version et me faire un retour ?

**Comment by The-MAD-Virus** [comment]
Super, je test ça ce soir.

**Comment by The-MAD-Virus** [comment]
Salut,
J'ai fait la mise ajour, mais n'a rien changer pour moi.

exemple de valeur pour la variable LTARF :

- HEURE PLEINE
- HEURE PLEINE77769
- HEURE PLEINE
- HEURE PLEINE77726
- HEURE PLEINE
- 677525

**Comment by tdouez** [comment]
@The-MAD-Virus , merci pour ce retour. Je ne vois pas de problématique dans le code avec une lecture approfondie. Je vais passer à l'étape sonde de bas niveau afin de voir si le problème vient de l'entrée TIC hardware ou logiciel, la partie librairie Teleinfo ou côté MySensors.

**Comment by The-MAD-Virus** [comment]
De mon coté je vais remplacer les cables entre le Linky et circuit imprimer, on ne sais jamais si ce n'est pas des signaux parasite qui interfère.
Après au niveau de la librairie le checksum se fait avec la date il me semble, peut être un problème de synchro ?

**Comment by tdouez** [comment]
@The-MAD-Virus et/ou @brag00n, vous tous les deux sous HA ? avez-vous la log brutes sortant de la gateway MySensors ? Est-ce que ces valeurs erronées sont déjà présentes ? Sur le code du module, il y a une vérif de checksum juste avant l'envoi des données MySensors donc les données sont correctes sans altération par des parasites.

**Comment by The-MAD-Virus** [comment]
J'ai fait le test ce week-end avec une liaison "_EMF Free_" entre Linky et le circuit, mais ça n'a rien changé.
Et pour répondre a ta question oui, j'utilise HA, il me semble que j'avais déjà regardé les log et les informations été identique.
Je vais quand même repasser HA en mode débug pour vérifié.

**Comment by tdouez** [comment]
@The-MAD-Virus, j'utilise actuelle le module RFM chez moi. Je vais remettre en ligne le module MySesnors et le surveiller de près (avec sonde) mais je suis personnellement en TIC standard et non historique mais le problème devrait aussi apparaître.
Question : as-tu la possibilité de mettre une sonde usb fdti sur l'arduino du module Linky ? Si oui, j'aurais besoin de ton aide ;)

**Comment by The-MAD-Virus** [comment]
Valeur erroné:
```sql
2023-02-13 16:36:53.346 DEBUG (MainThread) [mysensors.transport] Receiving 3;4;1;0;47;H PLE91657
2023-02-13 16:36:53.349 DEBUG (MainThread) [homeassistant.components.mysensors.gateway] Node update: node 3 child 4
2023-02-13 16:36:53.366 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NJOURF+1: value_type 47, value = 00
2023-02-13 16:36:53.367 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NJOURF+1: value_type 47, value = 00
2023-02-13 16:36:53.439 DEBUG (MainThread) [mysensors.transport] Receiving 3;7;1;0;18;6599145
2023-02-13 16:36:53.440 DEBUG (MainThread) [homeassistant.components.mysensors.gateway] Node update: node 3 child 7
2023-02-13 16:36:53.455 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NGTF: value_type 47, value = H PLE91657
2023-02-13 16:36:53.455 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NGTF: value_type 43, value = Wh
2023-02-13 16:36:53.455 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NGTF: value_type 47, value = H PLE91657
2023-02-13 16:36:53.455 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NGTF: value_type 43, value = Wh
```

Valeur correct:
```sql
2023-02-13 16:36:55.561 DEBUG (MainThread) [mysensors.transport] Receiving 3;5;1;0;47; HEURE  PLEINE  
2023-02-13 16:36:55.562 DEBUG (MainThread) [homeassistant.components.mysensors.gateway] Node update: node 3 child 5
2023-02-13 16:36:55.568 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NGTF: value_type 47, value = H PLEINE/CREUSE
2023-02-13 16:36:55.569 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NGTF: value_type 43, value = Wh
2023-02-13 16:36:55.569 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NGTF: value_type 47, value = H PLEINE/CREUSE
2023-02-13 16:36:55.569 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: NGTF: value_type 43, value = Wh
```

**Comment by tdouez** [comment]
Ok mais c'est des données déjà interprétée par HA. Au niveau de l'interface Mysensors, tu n'as pas la possibilité d'avoir les trames brutes Mysensors ?

**Comment by The-MAD-Virus** [comment]
> Question : as-tu la possibilité de mettre une sonde usb fdti sur l'arduino du module Linky ? Si oui, j'aurais besoin de ton aide ;)

OK, ce soir je branche le fdti et je tente d'enregistrer les logs.
As tu une idée de ce que tu cherche ? (le fichier risque d’être long).

**Comment by tdouez** [comment]
J’ai installé un HA sur mon pc et il est possible d’activer le journal de debug sur le Mysensors au niveau des appareils et services. Ensuite tu trouveras les trames brutes dans le journal de HA. Il est possible de le télécharger complètement.

Le 14 févr. 2023 à 12:35, The-MAD-Virus ***@***.***> a écrit :

﻿

Question : as-tu la possibilité de mettre une sonde usb fdti sur l'arduino du module Linky ? Si oui, j'aurais besoin de ton aide ;)

OK, ce soir je branche le fdti et je tente d'enregistrer les logs.
As tu une idée de ce que tu cherche ? (le fichier risque d’être long).

**Comment by The-MAD-Virus** [comment]
Le gateway MySensors est il coder avec option debug active ?
Parce que je ne vois pas les trames brute, j'ai le même résultat que j'ai poster précédemment. 
```sql
2023-02-13 16:36:55.561 DEBUG (MainThread) [mysensors.transport] Receiving 3;5;1;0;47; HEURE  PLEINE
```
Si on utilise le log parser de MySensors : [parser](https://www.mysensors.org/build/parser)

Sa nous donne :
<html><body>


Node Id | Child Sensor | Command Type | Echo Req/Resp | Type | Payload | Description
-- | -- | -- | -- | -- | -- | --
 3 | 4 | SET | false | V_TEXT | HEURE  PLEINE |  


</body>
</html>

**Comment by tdouez** [comment]
ok, ça marche. Reste à savoir si le problème est à la lecture la l'interface série. Pour cela, il faut ajouter un print lors de la lecture de l'entrée Serial; ce n'est pas dans le code actuellement.  Dans le fichier libTeleinfoLite.cpp, peut-tu ajouter la ligne suivant "Serial.print(c);"  juste avant la ligne "switch (c) {". Et ensuite reflasher le firmeware et mettre le connecteur FDTI pour récupérer la sortie Serial. Oui, c'est verbeux mais je ne vois pas comment faire autrement. De mon côté, je fais le test avec mon HA nouvellement installé.. bon je découvre et j'ai un peu de mal pour récupérer l'ensemble de mes étiquettes/entités...

**Comment by The-MAD-Virus** [comment]
Je n'ai pas pu logger plus long temps, je ne sais pas si cela suffira, mais voici le [lien](https://drive.google.com/file/d/1rdqIj8HZJYt0WQIQNJr_1tWqYOQUY0Pb/view?usp=share_link) du fichier.

ps: Je ne pourrai plus faire de tests dans les prochains jours, je pars en congé.

**Comment by tdouez** [comment]
Merci.
    Dans ce lot je n’ai pas vu de problème. En fait il faudrait avoir son pendant avec la log HA. Trouver le pb côté HA et voir si il existe côté arduino.

Le 15 févr. 2023 à 09:57, The-MAD-Virus ***@***.***> a écrit :

﻿

Je n'ai pas pu logger plus long temps, je ne sais pas si cela suffira, mais voici le lien<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1rdqIj8HZJYt0WQIQNJr_1tWqYOQUY0Pb%2Fview%3Fusp%3Dshare_link&data=05%7C01%7C%7Ce920eae6c2bf4d5d624308db0f329bbc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638120482248661975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ah8Et%2F3hM%2FKOR3kKx6i29wNgxkCf5tKEAqd7chBm9OM%3D&reserved=0> du fichier.

ps: Je ne pourrai plus faire de tests dans les prochains jours, je pars en congé.

**Comment by The-MAD-Virus** [comment]
J'ai refait des tests, mais bien sur pas de gros bug juste quel que valeur a zéro.
Je copie quand même un exemple où une valeur à zéro est envoyé.


Log HA :
```sql
2023-03-12 18:30:47.284 DEBUG (MainThread) [mysensors.transport] Receiving 3;53;1;0;38;0
2023-03-12 18:30:47.285 DEBUG (MainThread) [homeassistant.components.mysensors.gateway] Node update: node 3 child 53
2023-03-12 18:30:47.386 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: UMOY1: value_type 38, value = 0
2023-03-12 18:30:47.386 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: UMOY1: value_type 43, value = V
```

Log ftdi :
```sql
18:30:47:817 -> PCOUP	06	_3516359 TSF:MSG:SEND,3-3-0-0,s=33,c=1,t=55,pt=4,l=4,sg=0,ft=0,st=OK:6
18:30:47:896 -> 
18:30:47:896 -> SINSTS	01426	3305	07138	V
18:30:47:928 -> UMOY1	H2303E         		00	&
18:30:47:960 -> NJOUR6C001 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE	\
18:30:48:045 -> ADSC	041964289873	J3516589 TSF:MSG:SEND,3-3-0-0,s=1,c=1,t=47,pt=0,l=12,sg=0,ft=0,st=OK:041964289873
```

**Comment by tdouez** [comment]
de mon côté, j'ai installé HA mais je n'arrive pas à récupérer les étiquettes, je ne vous qu'une seule valeur "base". L"intégration mysensors Linky sous HA se réalise comment ? En modifiant le config yaml ?

**Comment by The-MAD-Virus** [comment]
Normalement si le Gateway est bien configurer les Nodes se mette a jour tout seul.
Quelle type de Gateway utilise tu ? (Sérial, Ethernet, MQTT)
Après il ce peut que, si tu as fait plusieurs test que le fichier qui sauvegarde les Nodes soit corrompu (MySensors#######.json).
Sa met déjà arriver, je l'ai simplement supprimer et redémarrer Home-Assitante pour repartir de zéro.
